import type { NextPage } from 'next';
import Head from 'next/head';

import TopTemplate from '@/components/templates/Top';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Raku Official Website</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <TopTemplate />
    </>
  );
};

export default Home;
